### ISSUE TITLE
Contributions or Change of Maintainer

### ISSUE THREAD

**Issue by joshdunnlime** [indigoviolet/conda-pip-minimal#6]
Hi @indigoviolet

I've noticed that the project has become somewhat stale and that things like Issues and PRs have gone un-replied to or unmanaged. Would you be happy to add me as a contributor or transfer maintenance and/or ownership to me. This is a really great project and tool a would love to make it even more useable by:
- adding it as conda package: https://github.com/indigoviolet/conda-pip-minimal/pull/3
- adding a license: https://github.com/indigoviolet/conda-pip-minimal/pull/3
- fixing semver only versions: https://github.com/indigoviolet/conda-pip-minimal/issues/5
- adding pre-commit hooks

and probably much more!

Please let me know if this is something you are interested in.

For now, I'll be working on a fork to get some more functionality working!

**Comment by indigoviolet** [comment]
Added you as collaborator - thank you for taking it on!

**Comment by joshdunnlime** [comment]
Amazing! Thanks Venky 🙏🏽
